name: Run Tests

on: [push]

jobs:
  RunUnitTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install pytest and plugins
        run: /usr/bin/pip3 install pytest pytest-describe pytest-mock
      - name: Run pytest
        run: /usr/bin/python3 -m pytest test_brute.py --color=yes

  RunFunctionalTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install chromedriver
        uses: nanasess/setup-chromedriver@master
      - name: Install behave
        run: /usr/bin/pip3 install behave behave-webdriver
      - name: Run HTTP Server
        run: nohup /usr/bin/python3 -m http.server 8000 &
             sleep 3
      - name: Run Functional Tests
        run: /usr/bin/python3 -m behave features
