name: Run Tests

on: [push]

jobs:
  RunUnitTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install pytest
        run: pip install pytest
      - name: Run pytest
        run: pytest --color=yes test_brute.py

  RunFunctionalTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install chromedriver
        uses: nanasess/setup-chromedriver@master
      - name: Install behave
        run: pip install behave behave-webdriver
      - name: Run HTTP Server
        run: nohup python3 -m http.server 8000 &
             sleep 3
      - name: Run Functional Tests
        run: behave features
